version: '3'
services:
  api:
    build:
      context: ../../api
    image: babaibeji/takehomeapi
    restart: on-failure
    ports:
      - '8084:8080'
    working_dir: /usr/src/app
    networks:
      - takehome-net

networks:
  takehome-net:
