kind: Deployment
apiVersion: apps/v1
metadata:
  name: api
  labels:
    service: api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      name: takehome
      labels:
        service: codematic
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/IMAGE:TAG
        name: api
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: NODE_ENV
      