name: gke

on: push

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: codematictest
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: codematictest
  IMAGE: codematictest

jobs:
  api:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test  
        run: npm test

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"

        # Deploy to GKE
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GKE_PROJECT }}
          APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_KEY }}
          CLUSTER_NAME: $GKE_CLUSTER
          ZONE_NAME: $GKE_ZONE
        with:
          args: apply -f k8s/ -n prod